all:
	rm *~

com:
	javac cs5530/*.java

run:
	java -cp ./mysql.jar:. cs5530.utrack


cpUser:
	scp cs5530/User.java User.class cs5530u25@georgia.eng.utah.edu:/home/cs5530u25/public_html/WEB-INF/classes/cs5530/
cpPOI:
	scp cs5530/POI.java POI.class cs5530u25@georgia.eng.utah.edu:/home/cs5530u25/public_html/WEB-INF/classes/cs5530/
cpUt:
	scp cs5530/utrack.java utrack.class cs5530u25@georgia.eng.utah.edu:/home/cs5530u25/public_html/WEB-INF/classes/cs5530/